export const PLAN_TYPE_FREE = 'FREE';

export const PLAN_TYPE_PAID = 'PAID';

export const USER_TYPE_CLIENTE = 'CLIENTE';

export const USER_TYPE_PROVEEDOR_SERVICES = 'SERVICIOS';

export const USER_TYPE_PROVEEDOR_PRODUCTS = 'PRODUCTS';
